### PR TITLE
option to check if data has missing values

### PR DESCRIPTION
**Pull request by johnhenrypezzuto**

### CODE REVIEW

**Comment by NickCH-K** [comment]
Is this preferable to the current approach to checking for missing values with summ="countNA(x)"?

**Comment by johnhenrypezzuto** [comment]
When glancing at a dataset I think a lot of people want a quick way to know if the data is complete or not. I thought this could be a nice shortcut.

**Comment by johnhenrypezzuto** [comment]
and the cost/risk of adding this option is low, no?

**Comment by NickCH-K** [comment]
Hmm, good point. And it would be simpler to use than summ.

**Review by NickCH-K — APPROVED** [review]

**Pull request merged**
